### ISSUE TITLE
Flushing an Image document closes the stream

### ISSUE THREAD

**Issue by gonzalovilaseca** [symfony-cmf/MediaBundle#128] opened 2015-04-29 16:13 UTC
Not sure if this is a MediaBundle issue or a Doctrine problem.
in this case:
```
$om->persist($image);
$om->flush();
$stream = $image->getFileContentAsStream()
```
``$stream`` is null, previous to the flush ``getFileContentAsStream`` returns a stream.

OTOH with this code:
```
$om->persist($image);
$om->flush();
$om->clear();
$image = $this->mr->getRepository($this->class)->find($image->getId());
$stream = $image->getFileContentAsStream()
```

``$stream`` is a valid stream.

Any ideas?

**Comment by dbu** [comment] 2015-04-29 21:55
hm, that is strange. we do wipe the stream from the property during the
save operation:
https://github.com/jackalope/jackalope/blob/master/src/Jackalope/Property.php#L269-L271
unfortunately i don't remember why exactly (that code is 4 years old,
after all) but i think it had to do with memory consumption and with
normalizing how streams look.

but the getBinary method is supposed to reload it immediately.
https://github.com/jackalope/jackalope/blob/master/src/Jackalope/Property.php#L308-L312

could this be a bug when wrapBinaryStreams is true? indeed there are
some illogic things in that method, as the value is unconditionally set
to null.

do you have time to investigate into this? we should create some unit
tests for the different flags i think, to check which cases work and
which dont. and then fix the cases that don't work.

**Comment by dbu** [comment] 2015-04-29 21:58
hm, just realized that your code is mapped on a document, so it would
also be something with what the unit of work does during the save - the
mystery deepens. but can you try playing with the Property class to
re-load the stream even if the streamwrapper is not enabled, or not set
the value to null, just to see on which layer the issue is?

**Comment by gonzalovilaseca** [comment] 2015-04-30 07:55
Ok, I will investigate and report back as soon as I find something.

**Comment by dbu** [comment] 2016-02-01 13:26
@gonzalovilaseca did you happen to find anything here?

**Comment by gonzalovilaseca** [comment] 2016-02-01 20:29
Sorry, I didn't.

**Comment by dbu** [comment] 2016-02-03 07:05
i will close this for now. if you find a way to reproduce it (ideally with a phpunit test in this bundle) please re-open or do a pull request with the failing test.

**Closed by dbu** 2016-02-03 07:05 UTC
Labels: bug
